on:
  push:
    branches: [main]
  pull_request:
jobs:
  conda:
    name: 
    runs-on: "macos-latest"
    steps:
      - run: mkdir -p catkin_ws/src
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          path: catkin_ws/src/aioros_bridge
      - name: Checkout aioros
        uses: actions/checkout@v3
        with:
          repository: mgrrx/aioros
          path: catkin_ws/src/aioros
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,defaults,robostack
          channel-priority: true
          auto-activate-base: false
          activate-environment: ""
      - shell: bash -l {0}
        run: |
          mamba create -n ros_env python=3.8
          conda activate ros_env
          mamba install catkin_tools rosdep ros-noetic-catkin ros-noetic-ros-environment
      - shell: bash -l {0}
        run: |
          conda activate ros_env
          cd catkin_ws
          rosdep init
          echo "yaml file://$PWD/src/aioros_bridge/rosdep.yaml" >> $CONDA_PREFIX/etc/ros/rosdep/sources.list.d/aioros_bridge.list
          rosdep update
          rosdep install -v -i --from-paths src -y
      - name: Build
        shell: bash -l {0}
        run: |
          conda activate ros_env
          cd catkin_ws
          catkin init
          catkin config --install
          catkin build
      - name: Test
        shell: bash -l {0}
        run: |
          conda activate ros_env
          cd catkin_ws
          . install/setup.bash
          catkin test aioros_bridge --no-deps
