on:
  push:
    branches: [main]
  pull_request:
jobs:
  conda:
    name: 
    runs-on: "ubuntu-latest"
    steps:
      - run: mkdir -p catkin_ws/src
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          path: catkin_ws/src/aioros_bridge
      - name: Checkout aioros
        uses: actions/checkout@v3
        with:
          repository: mgrrx/aioros
          path: catkin_ws/src/aioros
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          mamba-version: "*"
          channels: conda-forge,defaults,robostack
          channel-priority: true
      - shell: bash -l {0}
        run: |
          mamba install catkin_tools
